### ISSUE TITLE
[Definition Request]: Airdrop

### ISSUE THREAD

**Issue by cosisaxis** [narbs91/glosseta#128]
### Context

Airdrops are important to web3 because it brings awareness to a project which in turn creates a community around said project and within the web3 ecosystem, community is one of the important pillars of success.

### Term

Airdrops

### Definition

Airdrops are essentially when creators of a project send free coins or tokens to the wallets of users of their products to raise awareness around the project.

### List of category options

General (i.e. blockchain, fud, fomo, gm, etc...)

**Comment by narbs91** [comment]
Hi @cosisaxis , thank you so much for the issue creation!  Would you like to be assigned this issue?

Instructions on what this type of issue entails: https://github.com/narbs91/glosseta/wiki/How-to-guide:-Definition-intake-request
