### ISSUE TITLE
[Feature]: Word of the day

### ISSUE THREAD

**Issue by narbs91** [narbs91/glosseta#157]
### Context

A feature request was brought up recently for a "word of the day" to be added on the landing page so that people could have something to click into right away if they didn't know what to search for (consider someone completely new to the web3 space)

### Problem and/or Opportunity

With adding a word of the day on the landing page, the hope is that those new to web3 will have a starting point to begin diving into the content.  This feature is basically what the twitter handle is preforming today and can be used drive the content through twitter going forward

### Proposed Solution

Create a component that will sit between the logo and the search bar that will display a heading ("Word of the day") and a link to the definition of the word of the day.   The source of the word of the day will be driven though the [termConfig](https://github.com/narbs91/glosseta/blob/main/src/filter/termConfig.ts) file.  To pick the word to display on a given day, we can look perhaps utilize some modulo calculation around the given day (add the year, month, day) and the size of the term list  to come up with an index (or something similar).  Exact implementation will be left up to the implementor

**Figma file** : https://www.figma.com/file/CFNZbJNVaggeZHpETM5h2K/Glosseta-assets?node-id=64%3A15

### Testing the changes

Testing the changes will requires creating unit tests for the component, manually smoke testing and ensuring existing functionality is not broken.

**Comment by narbs91** [comment]
@cosisaxis here is a feature if you were looking to do some more coding oriented work

**Comment by alireza-jahandoost** [comment]
interested

**Comment by narbs91** [comment]
> interested

Hi @alireza-jahandoost thanks for stepping up, I'll assign the issue to you. Please let me know if you have any questions:)

**Comment by alireza-jahandoost** [comment]
Okay, thank you

**Comment by alireza-jahandoost** [comment]
@narbs91 It was my first time working with [Chakra-UI](https://chakra-ui.com/docs/getting-started) and [next-i18next](https://github.com/isaachinman/next-i18next). So please let me know if I've done anything wrong.
