### ISSUE TITLE
[Bug]: Misplacement the components

### ISSUE THREAD

**Issue by alireza-jahandoost** [narbs91/glosseta#160]
### What happened?

It seems that the place of some components is in `pages` directory, that makes them accessible from URL, that's not what we want. for example [this link](https://glosseta-nvz5mxw42-glosseta.vercel.app/components/footer/footer).
It may cause some other errors too, so all of the components from `src/pages/components` directory must be moved to `src/components` directory.

### How to reproduce the bug?

You can go to URLs like `basepath/components/component-name/component-name` to see the component.

### What browsers are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device type(s) did you see the problem on?

- [ ] Desktop
- [ ] Mobile
- [ ] Tablet

### What operating system(s) did you see the problem on?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by alireza-jahandoost** [comment]
I will be glad to fix this issue myself.

**Comment by narbs91** [comment]
> I will be glad to fix this issue myself.

Sounds great, i'll assign this issue to you, thank you!
