### ISSUE TITLE
[Definition Request]: beacon chain

### ISSUE THREAD

**Issue by narbs91** [narbs91/glosseta#87]
### Context

Taken from bigger issue: https://github.com/narbs91/glosseta/issues/44

### Term

beacon chain

### Definition

TBD

### List of category options

General (i.e. blockchain, fud, fomo, gm, etc...)

**Comment by naftalimurgor** [comment]
Hello,
I'd like to work on this topic. Let me know the steps I need so I can get started. Thank you!

**Comment by narbs91** [comment]
Hi @naftalimurgor thank you for taking the initiative and wanting to help add `beacon chain` to Glosseta's knowledge base!  I'll work on adding a wiki doc around the process of adding a definition and update this comment shortly after.  Essentially what your goal is to create a definition of the `beacon chain` in 2-3 sentences and add that to the [master csv file](https://github.com/narbs91/glosseta/blob/main/resources/master_term_bank_en.csv).  The aim of these definition requests is to provide a concise yet informative definition of term at hand.  Anyhow, i'll assign this issue to you and get working on that documentation

**Comment by narbs91** [comment]
Please find the aforementioned guide on how to work on a definition intake request issue in the following wiki page: https://github.com/narbs91/glosseta/wiki/How-to-guide:-Definition-intake-request

Please let me know if you have any questions/concerns

**Comment by narbs91** [comment]
Hi @naftalimurgor just checking in, any questions or concerns wrt to your assigned issue?

**Comment by naftalimurgor** [comment]
Hello, @narbs91 no questions, my apologies. I've been quite busy. Will submit a PR this week.
